### ISSUE TITLE
Not able to update Pwsh Core 6.2.3

### ISSUE THREAD

**Issue by lucasvc** [Ba4bes/PwshUpdateCheck#2]
Following [the blog's installation instruction](https://4bes.nl/2019/06/30/get-pwshupdates-check-if-there-is-a-powershell-update-available-and-install-it/),

```
$ Install-Script -Name Get-PwshUpdate
```

Has been stored in my home `C:\Users\lucasvc\Documents\PowerShell\Scripts`.

In a plain Pwsh Core shell,

```
$ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Fails,

```
$ Get-PwshUpdate.ps1
The shell is running in PowerShell Core while trying to install Core. Please run script in PowerShell Core Preview or Windows PowerShell.
At C:\Users\ventura\Documents\PowerShell\Scripts\Get-PwshUpdate.ps1:101 char:9
+         Throw "The shell is running in PowerShell Core while trying t ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (The shell is runnin\u2026Windows PowerShell.:String) [], RuntimeException
+ FullyQualifiedErrorId : The shell is running in PowerShell Core while trying to install Core. Please run script in PowerShell Core Preview or Windows PowerShell.
```

So, can't I update Core from a Core shell? Or what I misunderstood?

**Comment by Ba4bes** [comment]
Hi @lucasvc , 
That is correct, it is not possible with this script to install the update from the running shell. 
The reason for this is that the PowerShell Process would be running while it is being reinstalled, which can give issues. 
It is possible though to have PowerShell and PowerShell Preview running next to each other. In that case you can use one to update the other.

**Comment by lucasvc** [comment]
Now I understand the error log ^^;

But then, if I understood correctly, if I execute it from a (classic) PowerShell, it will try to update and/or install both PowerShell Core versions (normal and Preview one).

Executed now from,
```
$ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.771
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.771
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

I got,
```
$ Get-PwshUpdate.ps1
PowerShell 6-x64 : No Update needed
>> (opened pop-up to install Preview version)
Update canceled by user.
```

**Comment by Ba4bes** [comment]
The script should be able to check both versions like you expect. What pop-up did you receive? At what point does the script cancel itself? Did you press a button before or right after the popup?

**Comment by lucasvc** [comment]
![image](https://user-images.githubusercontent.com/1053448/70778498-bbaf4000-1d82-11ea-9aaa-83a4a0e60ae3.png)
This one. And after clicking on **\[No\]** appeared the cancel log. So works (IMHO) as expected that part.
So feel free to close this :)
Thanks again for your answers.

**Comment by Ba4bes** [comment]
Glad to help, let me know if anything else comes up 👍
